from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

from datetime import datetime
import os
import torch

# ==========================================================
# PDF REPORT GENERATOR
# ==========================================================

def generate_report(
    output_path,
    filename,
    file_type,
    prediction,
    confidence,
    probabilities,
    processing_time
):

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    doc = SimpleDocTemplate(output_path)

    story = []

    # ======================================================
    # TITLE
    # ======================================================

    story.append(
        Paragraph(
            "DeepFake Detection Report",
            title_style
        )
    )

    story.append(Spacer(1,0.3*inch))

    # ======================================================
    # DATE
    # ======================================================

    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    story.append(
        Paragraph(
            f"<b>Date & Time:</b> {current_time}",
            normal
        )
    )

    story.append(Spacer(1,0.2*inch))

    # ======================================================
    # FILE DETAILS
    # ======================================================

    story.append(Paragraph("File Details",heading))

    story.append(
        Paragraph(
            f"<b>Filename:</b> {filename}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>File Type:</b> {file_type}",
            normal
        )
    )

    story.append(Spacer(1,0.2*inch))

    # ======================================================
    # RESULT
    # ======================================================

    story.append(Paragraph("Prediction Result",heading))

    story.append(
        Paragraph(
            f"<b>Prediction:</b> {prediction}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2f} %",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Processing Time:</b> {processing_time:.3f} sec",
            normal
        )
    )

    story.append(Spacer(1,0.25*inch))

    # ======================================================
    # PROBABILITY TABLE
    # ======================================================

    story.append(Paragraph("Class Probabilities",heading))

    data = [
        ["Class","Probability (%)"],
        ["Fake",probabilities["Fake"]],
        ["Real",probabilities["Real"]]
    ]

    table = Table(data)

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.black),

            ("ALIGN",(0,0),(-1,-1),"CENTER"),

            ("BOTTOMPADDING",(0,0),(-1,0),10),

            ("BACKGROUND",(0,1),(-1,-1),colors.beige)

        ])
    )

    story.append(table)

    story.append(Spacer(1,0.3*inch))

    # ======================================================
    # SYSTEM INFORMATION
    # ======================================================

    story.append(Paragraph("System Information",heading))

    device = "GPU" if torch.cuda.is_available() else "CPU"

    story.append(
        Paragraph(
            f"<b>Device:</b> {device}",
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>AI Model:</b> EfficientNet-B0 + LSTM",
            normal
        )
    )

    story.append(Spacer(1,0.3*inch))

    # ======================================================
    # DEVELOPER
    # ======================================================

    story.append(Paragraph("Developer",heading))

    story.append(
        Paragraph(
            "Bhagya Patil",
            normal
        )
    )

    story.append(Spacer(1,0.2*inch))

    # ======================================================
    # DISCLAIMER
    # ======================================================

    story.append(Paragraph("Disclaimer",heading))

    story.append(
        Paragraph(
            "This prediction is generated by an AI model. "
            "It should be used only for research and educational purposes "
            "and should not be considered legal or forensic evidence.",
            normal
        )
    )

    doc.build(story)

    return output_path
if __name__ == "__main__":

    generate_report(

        output_path="reports/sample_report.pdf",

        filename="sample.jpg",

        file_type="Image",

        prediction="Fake",

        confidence=97.83,

        probabilities={
            "Fake":97.83,
            "Real":2.17
        },

        processing_time=0.42

    )

    print("Report Generated Successfully!")